### ISSUE TITLE
useSound 🔉 hook is not accepting all the parameters, including 'soundEnabled'

### ISSUE THREAD

**Issue by dmitrybirin** [jlengstorf/jason.af#20]
Hello! 👋 

You have really nice site in terms of knowledge and fun :) Thank you for doing all that!
It's a bit sketchy to file an issue to personal site, so think about it as friendly ray of information ⚡ 

So, found really small issue:
- Try to switch **off** the sound in settings
- The switch is turned off, localStorage setting updates
- Try to hover the setting button, or summon BOOP sound to the world
Result:
sound played 🔉 
Expected result:
no sound 🦗 🦗 🦗 

The problem should be 👉 [here](https://github.com/jlengstorf/jason.af/blob/daa59d6242c13a0b57bd10b494f2d56a631f8e20/src/hooks/use-sfx.js#L5):
useSound hook not accepting the `soundEnabled` parameter, that [passed into that](https://github.com/jlengstorf/jason.af/blob/daa59d6242c13a0b57bd10b494f2d56a631f8e20/src/hooks/use-sfx.js#L26), alongside `volume` and `interrupt`

Sorry for not PR, but `npm run dev` failed for me currently, so I think it's better do it like that.

Have a great day!

**Comment by jlengstorf** [comment]
oh no — I wonder what I did to break that 😂 

thanks for the heads up! I'll go figure out how I broke it and unbreak ~~my heart~~ this feature

**Comment by jlengstorf** [comment]
finally fixed this
